model:
  name: residual_unet_3d_global_weighted
  architecture: residual_unet_3d
  implementation: tfm_brats.monai_pipeline.FusionUNet
  in_channels: 4
  out_channels: 3
  channels: [16, 32, 64, 128]
  strides: [2, 2, 2]
  num_res_units: 2
  fusion: global_weighted
